version: '3.8'

services:
  rust-backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data/app:/usr/src/app
      - ./data/models:/usr/src/app/models
    command: ["image2nord"]
